In [1]:
import numpy as np

# Create array using Python list
arr = np.array([10, 20, 30, 40, 50])

# Display array
print("Array:", arr)

# Shape of array
print("Shape:", arr.shape)

# Data type
print("Data type:", arr.dtype)


Array: [10 20 30 40 50]
Shape: (5,)
Data type: int64


In [2]:
import numpy as np

# 3x4 matrix of zeros
zeros_matrix = np.zeros((3,4))

# 2x5 matrix of ones
ones_matrix = np.ones((2,5))

print("Zeros Matrix:")
print(zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\nOnes Matrix:")
print(ones_matrix)
print("Shape:", ones_matrix.shape)

Zeros Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

Ones Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [3]:
import numpy as np

# Create array from 1 to 12
arr = np.arange(1,13)

print("Original Array:")
print(arr)
print("Shape:", arr.shape)

# Reshape to 3x4
reshaped = arr.reshape(3,4)

print("\nReshaped Array:")
print(reshaped)
print("Shape:", reshaped.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [4]:
import numpy as np

# Random integers
arr = np.random.randint(1,100,10)

print("Array:", arr)

print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))

Array: [36 16  5 67 20 96 62 54  9 42]
Minimum: 5
Maximum: 96
Mean: 40.7
Sum: 407


In [5]:
import pandas as pd

data = {
    "Name": ["Amit", "Riya", "Karan", "Neha"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print(df)

print("\nData Types:")
print(df.dtypes)

    Name  Marks
0   Amit     85
1   Riya     90
2  Karan     78
3   Neha     92

Data Types:
Name       str
Marks    int64
dtype: object
